/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sickert.images;

import org.junit.jupiter.api.Test;
import org.sickert.images.Deduplicator;

import static org.junit.jupiter.api.Assertions.*;

class CliTest {
    @Test void appHasAGreeting() {
        Deduplicator classUnderTest = new Deduplicator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
