/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sickert.images.dedup;

public class Cli {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Cli().getGreeting());
    }
}
